test_that("MMEJ reference bundle layout and resolver find expected resources", {
  root <- tempfile("forgeki_ref_bundle_")
  dir.create(file.path(root, "mmej_stage10", "global"), recursive = TRUE)
  dir.create(file.path(root, "mmej_stage10", "gene_context", "CXCL10"), recursive = TRUE)
  dir.create(file.path(root, "hdr_stage10", "omics"), recursive = TRUE)
  global_path <- file.path(root, "mmej_stage10", "global", "20_MMEJ_CellLine_Ranking_Master.csv")
  gene_path <- file.path(root, "mmej_stage10", "gene_context", "CXCL10", "10A_HDR_TargetGene_CellLine_Context_Bundle.rds")
  omics_path <- file.path(root, "hdr_stage10", "omics", "forgeKI_stage10_omics_bundle.rds")
  writeLines("depmap_id,cell_line_name,Intrinsic_MMEJ_Global_Rank,MMEJ_Final_Tier,MMEJ_Risk_Class,Recommended_Use\nACH-1,A,1,Tier_1,Standard_Risk,Use", global_path)
  saveRDS(list(stage10d_ranking = tibble::tibble(CellLine_ID = "ACH-1", TargetGene_Activity_Component = 80)), gene_path)
  saveRDS(list(provenance = list(test = TRUE)), omics_path)

  layout <- forgeki_mmej_reference_bundle_layout(root, gene = "CXCL10")
  expect_true(any(layout$Resource_ID == "mmej_global_reference_preferred"))
  expect_equal(forgeki_resolve_mmej_reference(root, type = "global_cellline"), normalizePath(global_path, winslash = "/", mustWork = TRUE))
  expect_equal(forgeki_resolve_mmej_reference(root, gene = "CXCL10", type = "gene_context"), normalizePath(gene_path, winslash = "/", mustWork = TRUE))
  expect_equal(forgeki_resolve_mmej_reference(root, type = "hdr_stage10_omics_bundle"), normalizePath(omics_path, winslash = "/", mustWork = TRUE))

  chk <- forgeki_check_mmej_reference_bundle(root, genes = c("CXCL10", "EGFR"))
  expect_true(any(chk$Resource_ID == "mmej_global_cellline_reference" & chk$Status == "PASS_found"))
  expect_true(any(chk$Resource_ID == "hdr_stage10_omics_bundle" & chk$Status == "PASS_found"))
  expect_true(any(chk$Gene == "CXCL10" & chk$Status == "PASS_found"))
  expect_true(any(chk$Gene == "EGFR" & chk$Status == "WARN_missing"))
})

test_that("MMEJ bundle builder copies global and gene-context files", {
  src_dir <- tempfile("forgeki_bundle_src_"); dir.create(src_dir)
  global_src <- file.path(src_dir, "20_MMEJ_CellLine_Ranking_Master.csv")
  gene_src_dir <- file.path(src_dir, "CXCL10"); dir.create(gene_src_dir)
  gene_src <- file.path(gene_src_dir, "10A_HDR_TargetGene_CellLine_Context_Bundle.rds")
  omics_src <- file.path(src_dir, "hdr_stage10_omics_bundle.rds")
  writeLines("depmap_id,cell_line_name,Intrinsic_MMEJ_Global_Rank,MMEJ_Final_Tier,MMEJ_Risk_Class,Recommended_Use\nACH-1,A,1,Tier_1,Standard_Risk,Use", global_src)
  saveRDS(list(stage10d_ranking = tibble::tibble(CellLine_ID = "ACH-1")), gene_src)
  saveRDS(list(provenance = list(test = TRUE)), omics_src)

  root <- tempfile("forgeki_ref_bundle_build_")
  built <- forgeki_build_mmej_reference_bundle(root, global_src, gene_context_paths = gene_src, hdr_stage10_omics_bundle_path = omics_src)
  expect_true(file.exists(file.path(root, "manifest.csv")))
  expect_true(any(built$manifest$Resource_ID == "mmej_global_cellline_reference"))
  expect_true(any(built$manifest$Resource_ID == "hdr_stage10_omics_bundle"))
  expect_true(any(built$manifest$Gene == "CXCL10"))
  expect_true(file.exists(forgeki_resolve_mmej_reference(root, type = "global_cellline")))
  expect_true(file.exists(forgeki_resolve_mmej_reference(root, gene = "CXCL10", type = "gene_context")))
  expect_true(file.exists(forgeki_resolve_mmej_reference(root, type = "hdr_stage10_omics_bundle")))
})

test_that("hdr_stage10_options records reference_bundle_dir without changing explicit HDR paths", {
  root <- tempfile("forgeki_ref_bundle_cfg_")
  opt <- hdr_stage10_options(reference_bundle_dir = root, cellline_reference_path = "explicit_hdr.csv")
  expect_equal(opt$reference_bundle_dir, normalizePath(root, winslash = "/", mustWork = FALSE))
  expect_equal(opt$cellline_reference_path, normalizePath("explicit_hdr.csv", winslash = "/", mustWork = FALSE))
})
