`%||%` <- function(x, y) {
  if (is.null(x) || !length(x)) y else x
}

forgeki_stress_genes <- function() {
  c(
    "SELENOP", "KRAS", "HIST2H2BF", "TP53", "CDKN2A",
    "SMN1", "TTN", "AGO1", "MT-CO1", "POMC"
  )
}

forgeki_stress_methods <- function() c("HDR", "MMEJ")

forgeki_stress_risk_registry <- function() {
  list(
    SELENOP = list(
      disposition = "SCIENTIFIC GATE FAILURE",
      execute_pipeline = TRUE,
      risk = paste(
        "SELENOP uses SECIS-dependent selenocysteine recoding at in-frame UGA",
        "codons. A standard-code virtual translation can misinterpret those codons",
        "as premature stops, and a C-terminal edit must preserve recoding and 3' UTR",
        "regulatory biology."
      )
    ),
    KRAS = list(
      disposition = "SCIENTIFIC GATE FAILURE",
      execute_pipeline = TRUE,
      risk = paste(
        "KRAS requires an intact C-terminal CAAX motif for prenylation and membrane",
        "localization. A direct C-terminal fusion is scientifically unsafe without a",
        "specialized design that preserves terminal processing."
      )
    ),
    HIST2H2BF = list(
      disposition = "SCIENTIFIC GATE FAILURE",
      execute_pipeline = TRUE,
      risk = paste(
        "HIST2H2BF has a substantial histone-paralog burden and replication-dependent",
        "histone transcripts use specialized non-polyadenylated 3' processing.",
        "Gene-symbol resolution and locus specificity require manual validation."
      )
    ),
    TP53 = list(
      disposition = "SCIENTIFIC GATE FAILURE",
      execute_pipeline = TRUE,
      risk = paste(
        "TP53 produces biologically distinct alternative C-terminal isoforms.",
        "Automatically selecting one coding transcript does not establish that a",
        "C-terminal tag preserves the functions of the other isoforms."
      )
    ),
    CDKN2A = list(
      disposition = "SCIENTIFIC GATE FAILURE",
      execute_pipeline = TRUE,
      risk = paste(
        "CDKN2A encodes overlapping products in different reading frames.",
        "A transcript-specific C-terminal edit can disrupt the alternate product",
        "or shared genomic sequence and requires frame-aware manual design."
      )
    ),
    SMN1 = list(
      disposition = "SCIENTIFIC GATE FAILURE",
      execute_pipeline = TRUE,
      risk = paste(
        "SMN1 has a near-identical paralog, SMN2. Exact-match hg38 scanning alone",
        "does not resolve all near-match co-editing and allele-discrimination risk."
      )
    ),
    TTN = list(
      disposition = "REVIEW",
      execute_pipeline = TRUE,
      risk = paste(
        "TTN has extreme transcript length, extensive isoform diversity, and a",
        "complex locus. The selected terminal transcript and practical donor design",
        "must be interpreted in the intended tissue and isoform context."
      )
    ),
    AGO1 = list(
      disposition = "SCIENTIFIC GATE FAILURE",
      execute_pipeline = TRUE,
      risk = paste(
        "AGO1 is reported to undergo programmed stop-codon readthrough. Editing at",
        "the annotated stop can alter the canonical/readthrough product balance and",
        "is not adequately modeled by standard terminal-stop assumptions."
      )
    ),
    `MT-CO1` = list(
      disposition = "UNSUPPORTED BIOLOGY",
      execute_pipeline = FALSE,
      risk = paste(
        "MT-CO1 is mitochondrial, uses the mitochondrial genetic code, and is not a",
        "valid target for the package's nuclear hg38, SpCas9 donor-integration, and",
        "standard-code C-terminal workflow. The pipeline is intentionally not coerced",
        "through nuclear-gene assumptions."
      )
    ),
    POMC = list(
      disposition = "SCIENTIFIC GATE FAILURE",
      execute_pipeline = TRUE,
      risk = paste(
        "POMC is a secreted prohormone precursor whose biological products are",
        "generated by tissue-specific proteolytic processing. A terminal fusion to",
        "the precursor is not equivalent to tagging the mature functional peptides."
      )
    )
  )
}

forgeki_stress_risk <- function(gene) {
  registry <- forgeki_stress_risk_registry()
  registry[[toupper(gene)]] %||% list(
    disposition = "REVIEW",
    execute_pipeline = TRUE,
    risk = "No gene-specific risk rule is registered; manual interpretation is required."
  )
}

forgeki_stress_source_fingerprint <- function(package_root) {
  candidates <- c(
    file.path(package_root, "DESCRIPTION"),
    list.files(file.path(package_root, "R"), pattern = "\\.[Rr]$", full.names = TRUE),
    file.path(package_root, "tools", "stress_test_harness_lib.R"),
    file.path(package_root, "tools", "run_stress_test_matrix.R")
  )
  candidates <- sort(normalizePath(
    candidates[file.exists(candidates)],
    winslash = "/",
    mustWork = TRUE
  ))
  sums <- unname(tools::md5sum(candidates))
  digest::digest(
    paste(candidates, sums, sep = "=", collapse = "\n"),
    algo = "sha256",
    serialize = FALSE
  )
}

forgeki_stress_run_id <- function(gene, method, package_version, source_fingerprint) {
  method <- toupper(method)
  gene <- toupper(gene)
  spec <- paste(
    "forgeKI-stress-v1",
    gene,
    method,
    package_version,
    source_fingerprint,
    "hg38",
    "exact_hg38",
    "stage10=require",
    sep = "|"
  )
  hash <- substr(digest::digest(spec, algo = "sha256", serialize = FALSE), 1L, 16L)
  paste(tolower(method), gsub("[^A-Z0-9]+", "_", gene), hash, sep = "_")
}

forgeki_stress_timestamp <- function(time = Sys.time()) {
  format(time, "%Y%m%d_%H%M%S")
}

forgeki_stress_completed <- function(work_run_dir) {
  marker <- file.path(work_run_dir, "completed.json")
  if (!file.exists(marker)) return(FALSE)
  info <- tryCatch(jsonlite::read_json(marker, simplifyVector = TRUE), error = function(e) NULL)
  if (is.null(info) || is.null(info$curated_dir) || !dir.exists(info$curated_dir)) return(FALSE)
  identical(sort(list.files(info$curated_dir, all.files = FALSE)), sort(c("final_report.html", "run_audit.md")))
}

forgeki_stress_classify_error <- function(error_class, message, risk_disposition) {
  message_lc <- tolower(message %||% "")
  classes <- error_class %||% character()

  if (identical(risk_disposition, "UNSUPPORTED BIOLOGY")) {
    return("UNSUPPORTED BIOLOGY")
  }
  if (any(classes %in% c(
    "hdr_error_invalid_gene", "hdr_error_missing_resource",
    "hdr_error_cellline_reference_missing", "hdr_error_gene_context_reference_missing"
  )) || grepl("not found|missing resource|reference.*unavailable|no transcript records|none of the keys entered are valid keys", message_lc)) {
    return("INPUT/REFERENCE FAILURE")
  }
  if (grepl("cannot allocate|out of memory|package .* is required|there is no package|dependency", message_lc)) {
    return("ENVIRONMENT FAILURE")
  }
  if (any(classes %in% c(
    "hdr_error_no_hdr_usable_transcript", "hdr_error_no_guide_candidates",
    "hdr_error_no_valid_guides", "hdr_error_no_valid_designs"
  )) || grepl("no .*guide|no hdr-usable|no valid .*candidate|premature stop|internal stop", message_lc)) {
    return("SCIENTIFIC GATE FAILURE")
  }
  if (identical(risk_disposition, "SCIENTIFIC GATE FAILURE") &&
      grepl("virtual|translation|coding|stop codon|junction|reading frame", message_lc)) {
    return("SCIENTIFIC GATE FAILURE")
  }
  "IMPLEMENTATION DEFECT"
}

forgeki_stress_gate <- function(name, status, observed = NA_character_, expected = NA_character_) {
  allowed <- c("PASS", "FAIL", "SKIP", "NOT APPLICABLE")
  stopifnot(status %in% allowed)
  data.frame(
    Gate = name,
    Status = status,
    Observed = paste(observed, collapse = "; "),
    Expected = paste(expected, collapse = "; "),
    stringsAsFactors = FALSE
  )
}

forgeki_stress_first <- function(x, column, default = NA) {
  if (!is.data.frame(x) || !nrow(x) || !column %in% names(x)) return(default)
  x[[column]][[1]]
}

forgeki_stress_pass_status <- function(x) {
  is.character(x) && length(x) == 1L && !is.na(x) && grepl("^PASS", x)
}

forgeki_stress_md <- function(x) {
  x <- as.character(x %||% "")
  x[is.na(x)] <- "NA"
  gsub("\\|", "\\\\|", x)
}

forgeki_stress_markdown_table <- function(x) {
  if (!is.data.frame(x) || !nrow(x)) return("_No rows available._")
  values <- lapply(x, forgeki_stress_md)
  x <- as.data.frame(values, stringsAsFactors = FALSE)
  header <- paste0("| ", paste(names(x), collapse = " | "), " |")
  rule <- paste0("| ", paste(rep("---", ncol(x)), collapse = " | "), " |")
  rows <- apply(x, 1L, function(row) paste0("| ", paste(row, collapse = " | "), " |"))
  paste(c(header, rule, rows), collapse = "\n")
}

forgeki_stress_html_escape <- function(x) {
  x <- gsub("&", "&amp;", as.character(x), fixed = TRUE)
  x <- gsub("<", "&lt;", x, fixed = TRUE)
  x <- gsub(">", "&gt;", x, fixed = TRUE)
  x <- gsub("\"", "&quot;", x, fixed = TRUE)
  x
}

forgeki_stress_write_fallback_report <- function(path, record) {
  gate_html <- paste(
    apply(record$gates, 1L, function(row) {
      sprintf(
        "<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>",
        forgeki_stress_html_escape(row[["Gate"]]),
        forgeki_stress_html_escape(row[["Status"]]),
        forgeki_stress_html_escape(row[["Observed"]]),
        forgeki_stress_html_escape(row[["Expected"]])
      )
    }),
    collapse = "\n"
  )
  html <- c(
    "<!doctype html>",
    "<html><head><meta charset=\"utf-8\">",
    sprintf("<title>forgeKI stress test: %s %s</title>", record$method, record$gene),
    "<style>body{font-family:system-ui,sans-serif;max-width:1100px;margin:2rem auto;padding:0 1rem}table{border-collapse:collapse;width:100%}th,td{border:1px solid #bbb;padding:.4rem;text-align:left;vertical-align:top}code,pre{background:#f4f4f4;padding:.2rem}.FAIL{color:#a00;font-weight:bold}</style>",
    "</head><body>",
    sprintf("<h1>forgeKI %s stress test: %s</h1>", record$method, record$gene),
    sprintf("<p><strong>Run ID:</strong> <code>%s</code></p>", record$run_id),
    sprintf("<p><strong>Final classification:</strong> %s</p>", forgeki_stress_html_escape(record$classification)),
    sprintf("<p><strong>Pipeline status:</strong> %s</p>", forgeki_stress_html_escape(record$pipeline_status)),
    "<h2>Scientific interpretation</h2>",
    sprintf("<p>%s</p>", forgeki_stress_html_escape(record$risk$risk)),
    "<h2>Earliest root cause</h2>",
    sprintf("<pre>%s</pre>", forgeki_stress_html_escape(record$earliest_root_cause)),
    "<h2>Acceptance gates</h2>",
    "<table><thead><tr><th>Gate</th><th>Status</th><th>Observed</th><th>Expected</th></tr></thead><tbody>",
    gate_html,
    "</tbody></table>",
    "<p>This report was generated by the stress-test harness because the package report was unavailable or the pipeline was intentionally not executed.</p>",
    "</body></html>"
  )
  writeLines(html, path, useBytes = TRUE)
}

forgeki_stress_validate_curated_dir <- function(path) {
  identical(
    sort(list.files(path, all.files = FALSE)),
    sort(c("final_report.html", "run_audit.md"))
  )
}
